version: 2.1
jobs:
  cloud-storage-build:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - restore_cache:
          key: cloud-storage-dependency-cache-{{ checksum "pom.xml" }}
      - run:
          name: Build
          command: |
            java -version
            mvn scoverage:report
      - save_cache:
          key: cloud-storage-dependency-cache-{{ checksum "pom.xml" }}
          paths: ~/.m2
      - run:
          name: sonar
          command: |
            mvn -X sonar:sonar -Dsonar.projectKey=project-sunbird_sunbird-cloud-storage-sdk  -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=project-sunbird
workflows:
  version: 2.1
  workflow:
    jobs:
      - cloud-storage-build